### PR TITLE
ec_resource: Fix panic on empty DT resource kind

### LINKED ISSUE #129: Terraform Provider not supporting few ES Templates
The current version of terraform provider does not support creation of certain ES templates like CCS clusters.
The CCS clusters doesn't have an APM, Enterprise Search and App Search Resource.
The code currently checks them in the template API Response,  code checks need to be handled in this case.

## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
The CCS cluster should get created as per the template.

## Current Behavior
Getting the following error when running the terraform resource

```hcl
resource "ec_deployment" "defaults" {
  name                   = "ccs-cluster"
  region                 = "us-east-1"
  version                = "7.9.2"
  deployment_template_id = "aws-cross-cluster-search-v2"

  elasticsearch {
    topology {
      size = "1g"
    }
  }

  kibana {
    topology {
      size = "1g"
    }
  }
}
```

## Possible Solution
Add nil checks for APM and Enterprise Resources in deployment template.

## Steps to Reproduce
Run the terraform code provided above with the latest version of code.

## Context
Unable to create CCS cluster

## Your Environment

* Version used: master
* Environment name and version (e.g. Go 1.9): 1.13
* Server type and version: Mac
* Operating System and version: MacOS

### LINKED ISSUE #134: ec_deployment panics when using certain Deployment Templates
## Expected Behavior

`ec_deployment` should work with all deployment templates.

## Current Behavior

Introduced by #98 

It panics on templates which are missing `apm` or `enterprise_search` resources in the deployment template.

## Possible Solution

Return a default `*models.<kind>Payload`.

### PR DESCRIPTION
**Pull request by marclop**
## Description

Fixes a bug where any deployment template without all of the resources
(`Elasticsearch`, `Kibana`, `Apm` and `Enterprise Search`) present in
the `deployment_template` part of the template caused an index out of
bounds panic.

Adds unit and acceptance test cases.

## Related Issues

Closes #134 
Closes #129

## How Has This Been Tested?

All the possible ways.

## Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ggsood** [comment]
Fix looks good, thanks @marclop for looking into the issue and fixing it so quickly 😄

File: ec/ecresource/deploymentresource/expanders_deployment_template.go [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+// specific language governing permissions and limitations
+// under the License.
+
+package deploymentresource
+
+import "github.com/elastic/cloud-sdk-go/pkg/models"
+
+// esResource returns the ElaticsearchPayload from a deployment
+// template or an empty version of the payload.
+func esResource(res *models.DeploymentTemplateInfoV2) *models.ElasticsearchPayload {
```
Comment (karencfv) [inline ec/ecresource/deploymentresource/expanders_deployment_template.go:24]: I feel like each of these functions might make more sense in each of their `deploymentresource/<resource kind>_exapnders.go` files? I have a feeling that it would be simpler to read this way.

What do you think?

**Review by karencfv — COMMENTED** [review]
Thanks for fixing this bug!
